export const GET_BEST_FILMS_BY_YEAR = 'GET_BEST_FILMS_BY_YEAR';
export const GET_ALL_GENRES = 'GET_ALL_GENRES';
export const GET_FILM_BY_GENRES = 'GET_FILM_BY_GENRES';




export const SAVE_SELECTED_CHANNEL = 'SAVE_SELECTED_CHANNEL';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SAVE_SELECTED_CATEGORIES = 'SAVE_SELECTED_CATEGORIES';
export const GET_HEROES = 'GET_HEROES';
export const GET_SERIES = 'GET_SERIES';
export const GET_EPISODES = 'GET_EPISODES';
export const GET_MIX_PAGES = 'GET_MIX_PAGES';
export const SAVE_SELECTED_SERIALS = 'SAVE_SELECTED_SERIALS';
export const SAVE_SELECTED_EPISODE = 'SAVE_SELECTED_EPISODE';
export const SAVE_SELECTED_EPISODES = 'SAVE_SELECTED_EPISODES';
export const ADD_LOAD_IMAGE = 'ADD_LOAD_IMAGE';
export const ADD_TOTAL_LOAD_IMAGES = 'ADD_TOTAL_LOAD_IMAGES';
export const RESET_LOAD_IMAGES = 'RESET_LOAD_IMAGES';
export const SAVE_SELECTED_VIDEO = 'SAVE_SELECTED_VIDEO';
export const SAVE_NAME_SELECT_TAB = 'SAVE_NAME_SELECT_TAB';
export const SAVE_SELECT_ROUTE = 'SAVE_SELECT_ROUTE';



// just for auth and profile settings
export const SAVE_SELECT_SETTINGS = 'SAVE_SELECT_SETTINGS';
